version: '3.8'

services:

  db:
    image: postgres:15
    container_name: mmi_db
    environment:
      POSTGRES_DB: sae_db
      POSTGRES_USER: mmi_user
      POSTGRES_PASSWORD: mmi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mmi_backend
    depends_on:
      - db
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sae_db
      - SPRING_DATASOURCE_USERNAME=mmi_user
      - SPRING_DATASOURCE_PASSWORD=mmi_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  postgres_data: